# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Pipeline for Integration

on:
  push:
    branches: [ "main", "release/*"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-check:
    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 poetry
        poetry update
        
  unit-test:
    if: success() 
    runs-on: windows-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Testing the Unit test
      run: |
        test\unitTest.py
        
  Main-Module:
    if: success() 
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Running Main Module
      run: |
        src\fileCheck.py example\sourceFolder example\replicaFolder 5 src
